#!/bin/bash

if [ $1 -lt 2250000 ]
then
	if [ $1 -lt 1000 ]
	then
		REF_INCREMENT=$1 ./gxld -t=4 -f=192 -q=$1 -r=32768 -b=256 -k=64 -g=32
	else
		REF_INCREMENT=$(( $1 / 1000 )) ./gxld -t=4 -f=192 -q=$1 -r=32768 -b=256 -k=64 -g=32
	fi
else
	echo number of queries must be smaller than 2250000	
fi

